// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.service.newsfeed.rpc;

public interface ChildCommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChildComment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>string timeComment = 4;</code>
   */
  java.lang.String getTimeComment();
  /**
   * <code>string timeComment = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimeCommentBytes();
}
