// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.service.newsfeed.rpc;

/**
 * Protobuf type {@code Comment}
 */
public  final class Comment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Comment)
    CommentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Comment.newBuilder() to construct.
  private Comment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Comment() {
    userId_ = "";
    content_ = "";
    userAvatar_ = "";
    timeComment_ = "";
    childComments_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Comment(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userAvatar_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            timeComment_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              childComments_ = new java.util.ArrayList<web.service.newsfeed.rpc.ChildComment>();
              mutable_bitField0_ |= 0x00000010;
            }
            childComments_.add(
                input.readMessage(web.service.newsfeed.rpc.ChildComment.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        childComments_ = java.util.Collections.unmodifiableList(childComments_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return web.service.newsfeed.rpc.Newsfeed.internal_static_Comment_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return web.service.newsfeed.rpc.Newsfeed.internal_static_Comment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            web.service.newsfeed.rpc.Comment.class, web.service.newsfeed.rpc.Comment.Builder.class);
  }

  private int bitField0_;
  public static final int USERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userId_;
  /**
   * <code>string userId = 1;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string userId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 2;</code>
   */
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 2;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERAVATAR_FIELD_NUMBER = 3;
  private volatile java.lang.Object userAvatar_;
  /**
   * <code>string userAvatar = 3;</code>
   */
  public java.lang.String getUserAvatar() {
    java.lang.Object ref = userAvatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userAvatar_ = s;
      return s;
    }
  }
  /**
   * <code>string userAvatar = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserAvatarBytes() {
    java.lang.Object ref = userAvatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userAvatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMECOMMENT_FIELD_NUMBER = 4;
  private volatile java.lang.Object timeComment_;
  /**
   * <code>string timeComment = 4;</code>
   */
  public java.lang.String getTimeComment() {
    java.lang.Object ref = timeComment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeComment_ = s;
      return s;
    }
  }
  /**
   * <code>string timeComment = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTimeCommentBytes() {
    java.lang.Object ref = timeComment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeComment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHILDCOMMENTS_FIELD_NUMBER = 5;
  private java.util.List<web.service.newsfeed.rpc.ChildComment> childComments_;
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  public java.util.List<web.service.newsfeed.rpc.ChildComment> getChildCommentsList() {
    return childComments_;
  }
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  public java.util.List<? extends web.service.newsfeed.rpc.ChildCommentOrBuilder> 
      getChildCommentsOrBuilderList() {
    return childComments_;
  }
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  public int getChildCommentsCount() {
    return childComments_.size();
  }
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  public web.service.newsfeed.rpc.ChildComment getChildComments(int index) {
    return childComments_.get(index);
  }
  /**
   * <code>repeated .ChildComment childComments = 5;</code>
   */
  public web.service.newsfeed.rpc.ChildCommentOrBuilder getChildCommentsOrBuilder(
      int index) {
    return childComments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
    }
    if (!getUserAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userAvatar_);
    }
    if (!getTimeCommentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, timeComment_);
    }
    for (int i = 0; i < childComments_.size(); i++) {
      output.writeMessage(5, childComments_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
    }
    if (!getUserAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userAvatar_);
    }
    if (!getTimeCommentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, timeComment_);
    }
    for (int i = 0; i < childComments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, childComments_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof web.service.newsfeed.rpc.Comment)) {
      return super.equals(obj);
    }
    web.service.newsfeed.rpc.Comment other = (web.service.newsfeed.rpc.Comment) obj;

    boolean result = true;
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && getContent()
        .equals(other.getContent());
    result = result && getUserAvatar()
        .equals(other.getUserAvatar());
    result = result && getTimeComment()
        .equals(other.getTimeComment());
    result = result && getChildCommentsList()
        .equals(other.getChildCommentsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + USERAVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getUserAvatar().hashCode();
    hash = (37 * hash) + TIMECOMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeComment().hashCode();
    if (getChildCommentsCount() > 0) {
      hash = (37 * hash) + CHILDCOMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getChildCommentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static web.service.newsfeed.rpc.Comment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.newsfeed.rpc.Comment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static web.service.newsfeed.rpc.Comment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static web.service.newsfeed.rpc.Comment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(web.service.newsfeed.rpc.Comment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Comment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Comment)
      web.service.newsfeed.rpc.CommentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return web.service.newsfeed.rpc.Newsfeed.internal_static_Comment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return web.service.newsfeed.rpc.Newsfeed.internal_static_Comment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              web.service.newsfeed.rpc.Comment.class, web.service.newsfeed.rpc.Comment.Builder.class);
    }

    // Construct using web.service.newsfeed.rpc.Comment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChildCommentsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      userId_ = "";

      content_ = "";

      userAvatar_ = "";

      timeComment_ = "";

      if (childCommentsBuilder_ == null) {
        childComments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        childCommentsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return web.service.newsfeed.rpc.Newsfeed.internal_static_Comment_descriptor;
    }

    public web.service.newsfeed.rpc.Comment getDefaultInstanceForType() {
      return web.service.newsfeed.rpc.Comment.getDefaultInstance();
    }

    public web.service.newsfeed.rpc.Comment build() {
      web.service.newsfeed.rpc.Comment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public web.service.newsfeed.rpc.Comment buildPartial() {
      web.service.newsfeed.rpc.Comment result = new web.service.newsfeed.rpc.Comment(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.userId_ = userId_;
      result.content_ = content_;
      result.userAvatar_ = userAvatar_;
      result.timeComment_ = timeComment_;
      if (childCommentsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          childComments_ = java.util.Collections.unmodifiableList(childComments_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.childComments_ = childComments_;
      } else {
        result.childComments_ = childCommentsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof web.service.newsfeed.rpc.Comment) {
        return mergeFrom((web.service.newsfeed.rpc.Comment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(web.service.newsfeed.rpc.Comment other) {
      if (other == web.service.newsfeed.rpc.Comment.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getUserAvatar().isEmpty()) {
        userAvatar_ = other.userAvatar_;
        onChanged();
      }
      if (!other.getTimeComment().isEmpty()) {
        timeComment_ = other.timeComment_;
        onChanged();
      }
      if (childCommentsBuilder_ == null) {
        if (!other.childComments_.isEmpty()) {
          if (childComments_.isEmpty()) {
            childComments_ = other.childComments_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureChildCommentsIsMutable();
            childComments_.addAll(other.childComments_);
          }
          onChanged();
        }
      } else {
        if (!other.childComments_.isEmpty()) {
          if (childCommentsBuilder_.isEmpty()) {
            childCommentsBuilder_.dispose();
            childCommentsBuilder_ = null;
            childComments_ = other.childComments_;
            bitField0_ = (bitField0_ & ~0x00000010);
            childCommentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChildCommentsFieldBuilder() : null;
          } else {
            childCommentsBuilder_.addAllMessages(other.childComments_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      web.service.newsfeed.rpc.Comment parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (web.service.newsfeed.rpc.Comment) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userAvatar_ = "";
    /**
     * <code>string userAvatar = 3;</code>
     */
    public java.lang.String getUserAvatar() {
      java.lang.Object ref = userAvatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAvatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userAvatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserAvatarBytes() {
      java.lang.Object ref = userAvatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userAvatar = 3;</code>
     */
    public Builder setUserAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userAvatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userAvatar = 3;</code>
     */
    public Builder clearUserAvatar() {
      
      userAvatar_ = getDefaultInstance().getUserAvatar();
      onChanged();
      return this;
    }
    /**
     * <code>string userAvatar = 3;</code>
     */
    public Builder setUserAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userAvatar_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeComment_ = "";
    /**
     * <code>string timeComment = 4;</code>
     */
    public java.lang.String getTimeComment() {
      java.lang.Object ref = timeComment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeComment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeComment = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTimeCommentBytes() {
      java.lang.Object ref = timeComment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeComment = 4;</code>
     */
    public Builder setTimeComment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeComment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeComment = 4;</code>
     */
    public Builder clearTimeComment() {
      
      timeComment_ = getDefaultInstance().getTimeComment();
      onChanged();
      return this;
    }
    /**
     * <code>string timeComment = 4;</code>
     */
    public Builder setTimeCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeComment_ = value;
      onChanged();
      return this;
    }

    private java.util.List<web.service.newsfeed.rpc.ChildComment> childComments_ =
      java.util.Collections.emptyList();
    private void ensureChildCommentsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        childComments_ = new java.util.ArrayList<web.service.newsfeed.rpc.ChildComment>(childComments_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.newsfeed.rpc.ChildComment, web.service.newsfeed.rpc.ChildComment.Builder, web.service.newsfeed.rpc.ChildCommentOrBuilder> childCommentsBuilder_;

    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public java.util.List<web.service.newsfeed.rpc.ChildComment> getChildCommentsList() {
      if (childCommentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(childComments_);
      } else {
        return childCommentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public int getChildCommentsCount() {
      if (childCommentsBuilder_ == null) {
        return childComments_.size();
      } else {
        return childCommentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public web.service.newsfeed.rpc.ChildComment getChildComments(int index) {
      if (childCommentsBuilder_ == null) {
        return childComments_.get(index);
      } else {
        return childCommentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder setChildComments(
        int index, web.service.newsfeed.rpc.ChildComment value) {
      if (childCommentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildCommentsIsMutable();
        childComments_.set(index, value);
        onChanged();
      } else {
        childCommentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder setChildComments(
        int index, web.service.newsfeed.rpc.ChildComment.Builder builderForValue) {
      if (childCommentsBuilder_ == null) {
        ensureChildCommentsIsMutable();
        childComments_.set(index, builderForValue.build());
        onChanged();
      } else {
        childCommentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder addChildComments(web.service.newsfeed.rpc.ChildComment value) {
      if (childCommentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildCommentsIsMutable();
        childComments_.add(value);
        onChanged();
      } else {
        childCommentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder addChildComments(
        int index, web.service.newsfeed.rpc.ChildComment value) {
      if (childCommentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildCommentsIsMutable();
        childComments_.add(index, value);
        onChanged();
      } else {
        childCommentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder addChildComments(
        web.service.newsfeed.rpc.ChildComment.Builder builderForValue) {
      if (childCommentsBuilder_ == null) {
        ensureChildCommentsIsMutable();
        childComments_.add(builderForValue.build());
        onChanged();
      } else {
        childCommentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder addChildComments(
        int index, web.service.newsfeed.rpc.ChildComment.Builder builderForValue) {
      if (childCommentsBuilder_ == null) {
        ensureChildCommentsIsMutable();
        childComments_.add(index, builderForValue.build());
        onChanged();
      } else {
        childCommentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder addAllChildComments(
        java.lang.Iterable<? extends web.service.newsfeed.rpc.ChildComment> values) {
      if (childCommentsBuilder_ == null) {
        ensureChildCommentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, childComments_);
        onChanged();
      } else {
        childCommentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder clearChildComments() {
      if (childCommentsBuilder_ == null) {
        childComments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        childCommentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public Builder removeChildComments(int index) {
      if (childCommentsBuilder_ == null) {
        ensureChildCommentsIsMutable();
        childComments_.remove(index);
        onChanged();
      } else {
        childCommentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public web.service.newsfeed.rpc.ChildComment.Builder getChildCommentsBuilder(
        int index) {
      return getChildCommentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public web.service.newsfeed.rpc.ChildCommentOrBuilder getChildCommentsOrBuilder(
        int index) {
      if (childCommentsBuilder_ == null) {
        return childComments_.get(index);  } else {
        return childCommentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public java.util.List<? extends web.service.newsfeed.rpc.ChildCommentOrBuilder> 
         getChildCommentsOrBuilderList() {
      if (childCommentsBuilder_ != null) {
        return childCommentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(childComments_);
      }
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public web.service.newsfeed.rpc.ChildComment.Builder addChildCommentsBuilder() {
      return getChildCommentsFieldBuilder().addBuilder(
          web.service.newsfeed.rpc.ChildComment.getDefaultInstance());
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public web.service.newsfeed.rpc.ChildComment.Builder addChildCommentsBuilder(
        int index) {
      return getChildCommentsFieldBuilder().addBuilder(
          index, web.service.newsfeed.rpc.ChildComment.getDefaultInstance());
    }
    /**
     * <code>repeated .ChildComment childComments = 5;</code>
     */
    public java.util.List<web.service.newsfeed.rpc.ChildComment.Builder> 
         getChildCommentsBuilderList() {
      return getChildCommentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        web.service.newsfeed.rpc.ChildComment, web.service.newsfeed.rpc.ChildComment.Builder, web.service.newsfeed.rpc.ChildCommentOrBuilder> 
        getChildCommentsFieldBuilder() {
      if (childCommentsBuilder_ == null) {
        childCommentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            web.service.newsfeed.rpc.ChildComment, web.service.newsfeed.rpc.ChildComment.Builder, web.service.newsfeed.rpc.ChildCommentOrBuilder>(
                childComments_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        childComments_ = null;
      }
      return childCommentsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Comment)
  }

  // @@protoc_insertion_point(class_scope:Comment)
  private static final web.service.newsfeed.rpc.Comment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new web.service.newsfeed.rpc.Comment();
  }

  public static web.service.newsfeed.rpc.Comment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Comment>
      PARSER = new com.google.protobuf.AbstractParser<Comment>() {
    public Comment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Comment(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Comment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Comment> getParserForType() {
    return PARSER;
  }

  public web.service.newsfeed.rpc.Comment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

