// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsfeed.proto

package web.service.newsfeed.rpc;

public interface ShareRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShareRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string postId = 2;</code>
   */
  java.lang.String getPostId();
  /**
   * <code>string postId = 2;</code>
   */
  com.google.protobuf.ByteString
      getPostIdBytes();

  /**
   * <code>string content = 3;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
