// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.newsfeed.rpc;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserAvatarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserAvatarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserAvatarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserAvatarResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserNameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddNewImageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddNewImageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddNewImageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddNewImageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"&\n\024GetUserAvatarRequest\022\016\n\006" +
      "userId\030\001 \001(\t\"\'\n\025GetUserAvatarResponse\022\016\n" +
      "\006avatar\030\001 \001(\t\"$\n\022GetUserNameRequest\022\016\n\006u" +
      "serId\030\001 \001(\t\"\'\n\023GetUserNameResponse\022\020\n\010us" +
      "erName\030\001 \001(\t\"3\n\022AddNewImageRequest\022\r\n\005im" +
      "age\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\"&\n\023AddNewImage" +
      "Response\022\017\n\007success\030\001 \001(\0102\301\001\n\013UserServic" +
      "e\022>\n\rgetUserAvatar\022\025.GetUserAvatarReques" +
      "t\032\026.GetUserAvatarResponse\0228\n\013addNewImage" +
      "\022\023.AddNewImageRequest\032\024.AddNewImageRespo" +
      "nse\0228\n\013getUserName\022\023.GetUserNameRequest\032" +
      "\024.GetUserNameResponseB\037\n\030web.service.new" +
      "sfeed.rpcP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetUserAvatarRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetUserAvatarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserAvatarRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_GetUserAvatarResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetUserAvatarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserAvatarResponse_descriptor,
        new java.lang.String[] { "Avatar", });
    internal_static_GetUserNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetUserNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserNameRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_GetUserNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetUserNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserNameResponse_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_AddNewImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AddNewImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddNewImageRequest_descriptor,
        new java.lang.String[] { "Image", "UserId", });
    internal_static_AddNewImageResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AddNewImageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddNewImageResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
