// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.newsfeed.rpc;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserAvatarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserAvatarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserAvatarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserAvatarResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"&\n\024GetUserAvatarRequest\022\016\n\006" +
      "userId\030\001 \001(\t\"\'\n\025GetUserAvatarResponse\022\016\n" +
      "\006avatar\030\001 \001(\t2M\n\013UserService\022>\n\rgetUserA" +
      "vatar\022\025.GetUserAvatarRequest\032\026.GetUserAv" +
      "atarResponseB\037\n\030web.service.newsfeed.rpc" +
      "P\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetUserAvatarRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetUserAvatarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserAvatarRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_GetUserAvatarResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetUserAvatarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserAvatarResponse_descriptor,
        new java.lang.String[] { "Avatar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
