// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package web.service.newsfeed.rpc;

/**
 * Protobuf service {@code UserService}
 */
public  abstract class UserService
    implements com.google.protobuf.Service {
  protected UserService() {}

  public interface Interface {
    /**
     * <pre>
     * get user avatar
     * </pre>
     *
     * <code>rpc getUserAvatar(.GetUserAvatarRequest) returns (.GetUserAvatarResponse);</code>
     */
    public abstract void getUserAvatar(
        com.google.protobuf.RpcController controller,
        web.service.newsfeed.rpc.GetUserAvatarRequest request,
        com.google.protobuf.RpcCallback<web.service.newsfeed.rpc.GetUserAvatarResponse> done);

    /**
     * <pre>
     * user add image
     * </pre>
     *
     * <code>rpc addNewImage(.AddNewImageRequest) returns (.AddNewImageResponse);</code>
     */
    public abstract void addNewImage(
        com.google.protobuf.RpcController controller,
        web.service.newsfeed.rpc.AddNewImageRequest request,
        com.google.protobuf.RpcCallback<web.service.newsfeed.rpc.AddNewImageResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new UserService() {
      @java.lang.Override
      public  void getUserAvatar(
          com.google.protobuf.RpcController controller,
          web.service.newsfeed.rpc.GetUserAvatarRequest request,
          com.google.protobuf.RpcCallback<web.service.newsfeed.rpc.GetUserAvatarResponse> done) {
        impl.getUserAvatar(controller, request, done);
      }

      @java.lang.Override
      public  void addNewImage(
          com.google.protobuf.RpcController controller,
          web.service.newsfeed.rpc.AddNewImageRequest request,
          com.google.protobuf.RpcCallback<web.service.newsfeed.rpc.AddNewImageResponse> done) {
        impl.addNewImage(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.getUserAvatar(controller, (web.service.newsfeed.rpc.GetUserAvatarRequest)request);
          case 1:
            return impl.addNewImage(controller, (web.service.newsfeed.rpc.AddNewImageRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.service.newsfeed.rpc.GetUserAvatarRequest.getDefaultInstance();
          case 1:
            return web.service.newsfeed.rpc.AddNewImageRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return web.service.newsfeed.rpc.GetUserAvatarResponse.getDefaultInstance();
          case 1:
            return web.service.newsfeed.rpc.AddNewImageResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * get user avatar
   * </pre>
   *
   * <code>rpc getUserAvatar(.GetUserAvatarRequest) returns (.GetUserAvatarResponse);</code>
   */
  public abstract void getUserAvatar(
      com.google.protobuf.RpcController controller,
      web.service.newsfeed.rpc.GetUserAvatarRequest request,
      com.google.protobuf.RpcCallback<web.service.newsfeed.rpc.GetUserAvatarResponse> done);

  /**
   * <pre>
   * user add image
   * </pre>
   *
   * <code>rpc addNewImage(.AddNewImageRequest) returns (.AddNewImageResponse);</code>
   */
  public abstract void addNewImage(
      com.google.protobuf.RpcController controller,
      web.service.newsfeed.rpc.AddNewImageRequest request,
      com.google.protobuf.RpcCallback<web.service.newsfeed.rpc.AddNewImageResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return web.service.newsfeed.rpc.User.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.getUserAvatar(controller, (web.service.newsfeed.rpc.GetUserAvatarRequest)request,
          com.google.protobuf.RpcUtil.<web.service.newsfeed.rpc.GetUserAvatarResponse>specializeCallback(
            done));
        return;
      case 1:
        this.addNewImage(controller, (web.service.newsfeed.rpc.AddNewImageRequest)request,
          com.google.protobuf.RpcUtil.<web.service.newsfeed.rpc.AddNewImageResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.service.newsfeed.rpc.GetUserAvatarRequest.getDefaultInstance();
      case 1:
        return web.service.newsfeed.rpc.AddNewImageRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return web.service.newsfeed.rpc.GetUserAvatarResponse.getDefaultInstance();
      case 1:
        return web.service.newsfeed.rpc.AddNewImageResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends web.service.newsfeed.rpc.UserService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void getUserAvatar(
        com.google.protobuf.RpcController controller,
        web.service.newsfeed.rpc.GetUserAvatarRequest request,
        com.google.protobuf.RpcCallback<web.service.newsfeed.rpc.GetUserAvatarResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.service.newsfeed.rpc.GetUserAvatarResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.newsfeed.rpc.GetUserAvatarResponse.class,
          web.service.newsfeed.rpc.GetUserAvatarResponse.getDefaultInstance()));
    }

    public  void addNewImage(
        com.google.protobuf.RpcController controller,
        web.service.newsfeed.rpc.AddNewImageRequest request,
        com.google.protobuf.RpcCallback<web.service.newsfeed.rpc.AddNewImageResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.service.newsfeed.rpc.AddNewImageResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          web.service.newsfeed.rpc.AddNewImageResponse.class,
          web.service.newsfeed.rpc.AddNewImageResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public web.service.newsfeed.rpc.GetUserAvatarResponse getUserAvatar(
        com.google.protobuf.RpcController controller,
        web.service.newsfeed.rpc.GetUserAvatarRequest request)
        throws com.google.protobuf.ServiceException;

    public web.service.newsfeed.rpc.AddNewImageResponse addNewImage(
        com.google.protobuf.RpcController controller,
        web.service.newsfeed.rpc.AddNewImageRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public web.service.newsfeed.rpc.GetUserAvatarResponse getUserAvatar(
        com.google.protobuf.RpcController controller,
        web.service.newsfeed.rpc.GetUserAvatarRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.newsfeed.rpc.GetUserAvatarResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        web.service.newsfeed.rpc.GetUserAvatarResponse.getDefaultInstance());
    }


    public web.service.newsfeed.rpc.AddNewImageResponse addNewImage(
        com.google.protobuf.RpcController controller,
        web.service.newsfeed.rpc.AddNewImageRequest request)
        throws com.google.protobuf.ServiceException {
      return (web.service.newsfeed.rpc.AddNewImageResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        web.service.newsfeed.rpc.AddNewImageResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:UserService)
}

